apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: webcam-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: webcam
spec:
  host: webcam
  subsets:
  - name: discover-2
    labels:
      location: discover-2
  - name: discover-3
    labels:
      location: discover-3
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: webcam
spec:
  hosts:
  - "*"
  gateways:
  - webcam-gateway
  http:
    - route:
      - destination:
          host: webcam
          subset: discover-2
        weight: 70
      - destination:
          host: webcam
          subset: discover-3
        weight: 30
