apiVersion: v1
kind: Service
metadata:
  name: webcam
  labels:
    app: webcam
spec:
  type: ClusterIP
  ports:
  - port: 8888
    name: http
  selector:
    app: webcam
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcam-discover-2
#  labels:
#    app: webcam
#    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webcam
      location: discover-2
  template:
    metadata:
      labels:
        app: webcam
        location: discover-2
    spec:
      nodeSelector:
        kubernetes.io/hostname: discover-2
      containers:
      - name: webcam
        image: gongbaifei/webcam:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
        env:
          - name: CAM_ADDR
            value: 192.168.1.11
          - name: CAM_USR
            value: "admin"
          - name: CAM_PASSWD
            value: "admin"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcam-discover-3
#  labels:
#    app: webcam
#    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webcam
      location: discover-3
  template:
    metadata:
      labels:
        app: webcam
        location: discover-3
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-discover-3
      containers:
      - name: webcam
        image: gongbaifei/webcam:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
        env:
          - name: CAM_ADDR
            value: 192.168.1.11
          - name: CAM_USR
            value: "admin"
          - name: CAM_PASSWD
            value: "admin"
